# Generated by Django 3.2.4 on 2021-06-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickrapp', '0002_auto_20210625_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Photo title')),
                ('location', models.CharField(max_length=120)),
                ('date_uploaded', models.DateField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickrapp.album')),
            ],
            options={
                'ordering': ['date_uploaded'],
            },
        ),
    ]
